config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :games
  resources :bookings, only: [:new, :create, :edit, :show, :destroy, :index] do
    resources :reviews, only: [:new, :create, :show]
  end
  resources :reviews, only: :destroy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :game
  has_many :reviews, dependent: :destroy
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user
  validates :content, length: { minimum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games
  has_many :bookings
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user: current_user)
    @review = Review.new
    @game = Game.new
  end

  def new
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:id])
    @review = Review.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
    @booking = booking.find(params[:id])
    @booking.update(booking_params)
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private
  def booking_params
    params.require(:booking).permit(:id, :duration, :user_id, :game_id)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    game = Game.new(game_params)
    game.user = current_user
    if game.save
      flash[:notice] = "Your game posted successfully "
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @game = Game.find(params[:id])
  end
  def update
    @game = Game.find(params[:id])
    @game.update(params[:game])
    redirect_to game_path(@game)
  end
  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path
  end
  private

  def game_params
    params.require(:game).permit(:title, :description, :daily_price, :address, :category, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    
    # if params are there 
    # then filter with .where(..)
    # else
    # just Game.all
    
    if params[:category].present?
     @games = Game.where(category: params[:category])
    else
    @games = Game.all
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    @review.user = current_user
    if @review.save
      redirect_to game_path(@booking.game)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1 class="booking-title">Your bookings</h1>
<div class="bookings-grid">
    <% @bookings.each do |booking| %>
  <div class="bookings-container">

    <div class="card border-dark mb-3">
      <h1 class="card-header" style="text-align: center;"><%= booking.game.title %></h1>
        <div class="booking-content">
          <p>Starting date: <%= booking.created_at.strftime('%d/%m/%y') %></p>
          <p> Remember to return the game on <%= (booking.created_at + (86400 * booking.duration)).strftime('%d/%m/%y') %> </p>
          <div class="game-img-bookings">
          <% link_to  %>
            <% if booking.game.photo.attached? %>
              <%= cl_image_tag booking.game.photo.key, height: 120, width: 120, crop: :fill, class: "show-image" %>
            <% else %>
              <%= image_tag 'no_image.png', height: 120, width: 120 %>
            <% end %>
          </div>
          <strong><%= link_to "Delete booking" ,
                        booking_path(booking),
                        method: :delete,
                        data: { confirm: "Are you sure?" } %></strong>
        </div>
      </div>
      <div class="review-form">
        <%= simple_form_for([ booking, Review.new ]) do |form| %>
          <%= form.input :content, as: :text, label: 'Review'%>
          <%= form.input :rating, :collection => %w[1 2 3 4 5] %>
          <%= form.button :submit, "Review" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<%= @booking.duration %>

app/views/bookings/show.html.erb
<div class="show-container">
  <h1 class="booking-title">Your booking</h1>
  <div class="card">
    <div class="card-body">
      <h3 class="card-title"><%= @booking.game.title %></h3>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Duration: <%= @booking.duration %> days</li>
      <li class="list-group-item">Starting at: <%= @booking.created_at.strftime('%d/%m/%y') %></li>
      <li class="list-group-item">Finishing at: <%= (@booking.created_at + (86400 * @booking.duration)).strftime('%d/%m/%y') %> </li>
      <li class="list-group-item">Price to Pay: £ <%= @booking.game.daily_price * @booking.duration %></li>
    </ul>
  </div>
</div>

app/views/games/new.html.erb
<div class="new-container">
   <div class="row justify-content-center">
    <div class="col-lg-6">
      <%= simple_form_for @game do |f| %>
      <%= f.input :title, placeholder: 'e.g. Call of Duty', class: "in" %>
      <%= f.input :category, collection: ['Action', 'Adventure', 'Casual', 'MMO', 'Racing', 'RPG', 'Sports', 'Strategy']%>
      <%= f.input :description, placeholder:'Call of Duty is a first-person shooter video game franchise published by Activision', as: :text%>
      <%= f.input :daily_price, placeholder: "£££"%>
      <%= f.input :address, placeholder: "e.g. London, Kingsland Road N27 6GT" %>
      <%= f.input :photo, as: :file, class: "upload" %>
      <%= f.submit "Submit", class: "btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="show-container">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="show-form">
        <h1><%= @game.title %></h1>
          <% if @game.photo.attached? %>
            <%= cl_image_tag @game.photo.key, height: 200, width: 300, crop: :fit, class: "show-image" %>
          <% else %>
            <%= image_tag 'no_image.png', height: 200, width: 300, crop: :fit %>
          <% end %>
        <p><strong><%=@game.category %></strong></p>

        <p><strong>Description:</strong> <%= @game.description %></p>
        <p>£<%= @game.daily_price %> per day</p>
        <p><%= @game.address %></p>
        <%= simple_form_for Booking.new do |f| %>
        <%= f.hidden_field :game_id, value: @game.id %>
        <strong><%= f.input :duration, :collection => %w[3 5 7 14] %></strong>
        <%= f.submit "Book", class: "btn" %>
        <% end %>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="review-holder">
          <h3>Reviews</h3>
        <% @game.reviews.each do |review| %>
          <div class="review-card">
            <p><%= "*" * review.rating %></p>
            <p><%= review.content %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamehub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Krona+One|Roboto:400,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div style="min-height: calc(100vh - 122px)">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= asset_url("game_banner_1.jpg") %>');">
  <div class="container-banner">
    <h1 class="title">GameHub</h1>
    <p>Get your game on!</p>
    <div>
      <%= link_to "Rent out your game!", new_game_path, class: "nav-link btn call-action cat-back-pulse" %>
    </div>
  </div>
</div>
<div class="container-card-form">
  <div class="row w-75" >
    <% @games.each do |game| %>
      <div class="col-4 pb-3">

        <% if game.photo.attached? %>

          <div class="game-card">
            <div class="game-image" style="background-image: url('<%= cl_image_path game.photo.key, height: 165, width: 300 , crop: :fit %>'); background-repeat: no-repeat; background-position: center;">
            </div>
            <div class="game-card-info">
              <div class="game-card-title">
                <h3><%= link_to game.title, game_path(game) %></h3>
                <p class="test-ben"><%= game.category %></p>
              </div>
              <p class="game-price">£<%= game.daily_price %></p>
            </div>
          </div>
        <%else %>
        <div class="game-card">
            <div class="game-image" style="background-image: url('<%= image_path 'no_image.png', height: 165, width: 300 %>')">
            </div>
            <div class="game-card-info">
             <div class="game-card-title">
              <h3><%= link_to game.title, game_path(game) %></h3>
               <p class="test-ben"><%= game.category %></p></div>
              <p class="game-price">£<%= game.daily_price %></p>
        </div>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="cat-container">
    <!-- <h2 class="categories">
      CATEGORIES
    </h2> -->
    <li class="cat-list">
      <ul><%= link_to 'All Categories', root_path, class: "cat-btn cat-back-pulse" %></ul>
      <hr>

      <ul><%= link_to 'Action', root_path(category: 'Action'), class: "cat-btn cat-back-pulse" %></ul>
      <hr>
      <ul><%= link_to 'Adventure', root_path(category: 'Adventure'), class: "cat-btn cat-back-pulse" %></ul>
      <hr>
      <ul><%= link_to 'Casual', root_path(category: 'Casual'), class: "cat-btn cat-back-pulse" %></ul>
      <hr>
      <ul><%= link_to 'MMO', root_path(category: 'MMO'), class: "cat-btn cat-back-pulse" %></ul>
      <hr>
      <ul><%= link_to 'Racing', root_path(category: 'Racing'), class: "cat-btn cat-back-pulse" %></ul>
      <hr>
      <ul><%= link_to 'RPG', root_path(category: 'RPG'), class: "cat-btn cat-back-pulse" %></ul>
      <hr>
      <ul><%= link_to 'Sports', root_path(category: 'Sports'), class: "cat-btn cat-back-pulse" %></ul>
      <hr>
      <ul><%= link_to 'Strategy', root_path(category: 'Strategy'), class: "cat-btn cat-back-pulse" %></ul>
    </li>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.facebook.com/GameHub-108907714045753/?modal=admin_todo_tour" target="_blank"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright">
    This page is made with <i class="fas fa-heart"></i> at <span class="target">THE GAMEFREAKS!</span>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="logo-group">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "gamehub_logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

</div>
  <%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="form-group form-inline mt-3 d-flex">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn">Search
    </button>
  </div>
<% end %>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "btn" %>
          <%= link_to "Rent out!", new_game_path, class: "btn" %>
          <%= link_to "Bookings", bookings_path, class: "btn" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "victor_avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item d-flex">
          <%= link_to "Sign up", new_user_registration_path, class: "btn" %>
          <%= link_to "Login", new_user_session_path, class: "btn" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>